name: Automatic release

on:
  push:
    tags:
    - '*'

jobs:
  build:
    env:
      TIMESTAMP_TAG: ''
      RELEASE_TITLE: ''
    runs-on: ubuntu-latest
    container:
      image: kleinspeedy/thesis-builder
    steps:
      - name: Setup
        uses: actions/checkout@v3
      - name: Build pdf
        run: ./skripte/2pdf.sh
      - name: Release title
        run: |
          echo "RELEASE_TITLE=$(date -d @${{ github.ref }} --rfc-3339=seconds)" >> $GITHUB_ENV
      - name: Publish pdf
        uses: ncipollo/release-action@v1
        with:
          name: "${{ env.RELEASE_TITLE }}"
          token: "${{ secrets.PDF_TOKEN }}"
          artifacts: "*.pdf"
