on:
  push:
    branches:
      - main
jobs:
  build:
    env:
      TIMESTAMP_TAG: ''
      RELEASE_TITLE: ''
    runs-on: ubuntu-latest
    container:
      image: kleinspeedy/thesis-builder
    steps:
      - name: Setup
        uses: actions/checkout@v3
      - name: Build pdf
        run: ./skripte/2pdf.sh
      - name: Release tag
        run: |
          echo "TIMESTAMP_TAG=$(date +"%s")" >> $GITHUB_ENV
      - name: Release title
        run: |
          echo "RELEASE_TITLE=$(date -d @$TIMESTAMP_TAG --rfc-3339=seconds)" >> $GITHUB_ENV
      - name: Publish pdf
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.PDF_TOKEN }}"
          automatic_release_tag: ${{ env.TIMESTAMP_TAG }}
          title: "${{ env.RELEASE_TITLE }}"
          files: |
            *.pdf
